name: Development build

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_run:
    workflows: [Lint]
    types: [completed]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # extract-branch:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   outputs:
  #     branch: ${{ steps.extract_branch.outputs.branch }}
  #   steps:

  #     - name: Extract branch name
  #       shell: bash
  #       run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
  #       id: extract_branch

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest-develop:
    needs: extract-branch
    runs-on: ubuntu-latest
    # if: ${{ needs.extract-branch.outputs.branch == 'develop' }}
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run:  docker-compose -f local.yml build

      - name: Run DB Migrations
        run:  docker-compose -f local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run:  docker-compose -f local.yml run django pytest

      - name: Tear down the Stack
        run:  docker-compose -f local.yml down
